//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jarvis_Phase3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int deviceID { get; set; }
        public string category { get; set; }
        public int accountID { get; set; }
        public int dataID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual DeviceData DeviceData { get; set; }
        public virtual StoredData StoredData { get; set; }
    }
}
