//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jarvis_Phase3
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoredData
    {
        public int deviceID { get; set; }
        public string state { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
